# 网站 URL ，最后勿加入斜杠
url: http://www.hljscqnn.com

# 网站名称
name: 广东广州办事处

# 默认标题
title: 全能保险柜广东广州办事处

# 默认关键词
keywords: 广州保险柜

# 默认描述
description: 广东安能保险柜制造有限公司旗下QNNsafe全能保险柜是国内保险柜十大品牌之一，专业制造保险柜、保险箱、家用保险柜、家用保险箱等安防产品。

# 备案号
beian: 粤ICP备12015444号-2

# 右上角电话
telephone: 020-84224868

# QQ客服1号
qq1: 904381538

# QQ客服1号
qq2: 200802811

# 百度地图坐标，到这里获取： http://api.map.baidu.com/lbsapi/getpoint/
coord: 113.28,22.76

# 百度地图框内地址
addr: 地址：广东省广州市越秀区东风东路532号

# 自定各产品的淘宝链接，default是默认链接（可以填上店铺主页），产品用名称（name字段，如BW-6960）对应网址
taobao:
  default: http://www.taobao.com/
  B-4538: 
  B-5440: 
  B-7348: 
  BGX-2535: 
  BGX-5840: 
  BMG-7545A/B: 
  BMG-8001A/B: 
  BMG-8002A/B: 
  BMG-8003A/B: 
  BMG-9055A/B: 
  BP-6747: 
  BP-9050: 
  BW-6960: 
  CKI-253525: 
  CM-2045: 
  CM-2045ZH: 
  CS-2018D: 
  CS-2221D: 
  CS-2520C: 
  CS-4021C: 
  CT-1211: 
  CT-1211H: 
  CT-4013: 
  CT-4013ME: 
  CT-4013ZH: 
  CT-4018ZH: 
  CW-7348: 
  C型不带枪锁枪弹柜: 
  C型枪弹柜系列: 
  DG-6442DS: 
  DG-7645D: 
  DG-7645S: 
  DG-9150D: 
  DG-9150S: 
  DM-2146: 
  DM-2146ZH: 
  D型零头弹药柜: 
  ES-2045ZH: 
  ES-2318W: 
  E型部队专用携行枪柜: 
  F-1614C: 
  F-2014C/K/E: 
  F-2714C/K/E: 
  F-2720ICK: 
  F-2720ILK: 
  F-3020C/E: 
  F-3020CC/EE: 
  F-3214CC/EE: 
  F-3214CCM/EEM: 
  F-4020ILK: 
  FG-100B/R: 
  FG-11860B/R: 
  FG-153: 
  FG-15870B/R: 
  FG-2940B/R: 
  FG-3001: 
  FG-3002: 
  FG-3542B/R: 
  FG-5840B/R: 
  FG-6001: 
  FG-6002: 
  FG-6006: 
  FG-6024F: 
  FG-6030F: 
  FG-6842B/R: 
  FG-8045B/R: 
  FG-9150B/R: 
  FG-9150D: 
  FRD-21: 
  FRD-31: 
  FRD-42: 
  GLF-3340: 
  GLF-4540: 
  GLF-5842: 
  GLF-7042: 
  GLF-7550: 
  GLF-8550: 
  GTX-11860: 
  GTX-15870: 
  GTX-3345: 
  GTX-4542: 
  GTX-5842: 
  GTX-6845: 
  GTX-9050: 
  H-06: 
  H-12: 
  H-15: 
  HG-11860: 
  HG-15870: 
  HG-2740: 
  HG-3342: 
  HG-4538: 
  HG-5840: 
  HG-6842: 
  HG-7645D: 
  HG-8045: 
  HG-9150: 
  IF-1212SC: 
  IF-1500C: 
  IF-2500C: 
  IF-3000C: 
  ITG-2040: 
  ITG-3342: 
  ITG-5840: 
  JKM(B)-1020-N: 
  JKM(CS)-1020-N: 
  JKM(M)-1020-N: 
  KL-4045: 
  MA-2045ZH: 
  MB-2045UZH: 
  MF-2043ZH: 
  MG-2043ZH: 
  MG-2045: 
  MH-2043ZH: 
  MI-2045: 
  MI-2045UZH: 
  MK-2043ZH: 
  MQ-2045ZH: 
  QN-2043: 
  QN-2043ZH: 
  RH-1612K/C: 
  RH-2014C/K/E: 
  RH-2410C/K: 
  RH-3020CC: 
  SJB-1630B/R: 
  SJB-2243B/R: 
  SJB-3236B/R: 
  SJB-40HⅢB/R: 
  SJB-40ⅢB/R: 
  SJB-43ⅢB/R: 
  SJB-48ⅢB/R: 
  SJB-52ⅢB/R: 
  SJB-53ⅢB/R: 
  SJB-58ⅢB/R: 
  SJB-72ⅢB/R: 
  SJB-88ⅢB/R: 
  SJB-88ⅢDB/R: 
  SK-2045: 
  SK-2045ZH: 
  TGG-2040B/R: 
  TGG-2045B/R: 
  TGG-2740B/R: 
  TGG-3342B/R: 
  TGG-4538B/R: 
  TGG-4938B/R: 
  TGG-5840B/R: 
  TGG-6642B/R: 
  TGG-7645B/R: 
  US-1206K: 
  US-1C/K: 
  US-2C/K: 
  US-3C/K: 
  WS-108: 
  ZA-18090: 
  ZF-4538B/R: 
  ZF-4938B/R: 

permalink: /products/:title.html

relative_permalinks: false

exclude:
  - README.md
  - css
  - js

assets:
  dirname: assets
  baseurl: /assets/
  sources:
    - js
    - css
  js_compressor: uglifier
  css_compressor: sass
  cache: true
  cache_assets: true
  gzip: []
